package gui;
public class ClerkMenuPanel extends javax.swing.JPanel {

    /** Creates new form ClerkMenu */
    public ClerkMenuPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listclientwithoutstandingbalanceButton = new javax.swing.JButton();
        savedatabaseButton = new javax.swing.JButton();
        loaddatabaseButton = new javax.swing.JButton();
        processPaymentButton = new javax.swing.JButton();
        addProductButton = new javax.swing.JButton();
        addManufacturerButton = new javax.swing.JButton();
        addclientButton = new javax.swing.JButton();
        receiveShipmentButton = new javax.swing.JButton();
        listSuppliersButton = new javax.swing.JButton();
        listallProductwithQuantityButton = new javax.swing.JButton();
        shipfromWaitListButton = new javax.swing.JButton();
        processClientOrderButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        logoutButton = new javax.swing.JButton();
        topLabel = new javax.swing.JLabel();
        backButton1 = new javax.swing.JButton();
        becomeClientButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(420, 450));
        setMinimumSize(new java.awt.Dimension(420, 450));
        setPreferredSize(new java.awt.Dimension(420, 450));

        listclientwithoutstandingbalanceButton.setText("List Clients With Outstanding Backorders");
        listclientwithoutstandingbalanceButton.setMaximumSize(new java.awt.Dimension(420, 420));
        listclientwithoutstandingbalanceButton.setMinimumSize(new java.awt.Dimension(420, 420));
        listclientwithoutstandingbalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listclientwithoutstandingbalanceButtonActionPerformed(evt);
            }
        });

        savedatabaseButton.setText("Save Database");
        savedatabaseButton.setMaximumSize(new java.awt.Dimension(420, 420));
        savedatabaseButton.setMinimumSize(new java.awt.Dimension(420, 420));
        savedatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedatabaseButtonActionPerformed(evt);
            }
        });

        loaddatabaseButton.setText("Load Database");
        loaddatabaseButton.setMaximumSize(new java.awt.Dimension(420, 420));
        loaddatabaseButton.setMinimumSize(new java.awt.Dimension(420, 420));
        loaddatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaddatabaseButtonActionPerformed(evt);
            }
        });

        processPaymentButton.setText("Process Payment");
        processPaymentButton.setMaximumSize(new java.awt.Dimension(420, 420));
        processPaymentButton.setMinimumSize(new java.awt.Dimension(420, 420));
        processPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processPaymentButtonActionPerformed(evt);
            }
        });

        addProductButton.setText("Add Product");
        addProductButton.setMaximumSize(new java.awt.Dimension(420, 420));
        addProductButton.setMinimumSize(new java.awt.Dimension(420, 420));
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        addManufacturerButton.setText("Add Manufacturer");
        addManufacturerButton.setMaximumSize(new java.awt.Dimension(420, 420));
        addManufacturerButton.setMinimumSize(new java.awt.Dimension(420, 420));
        addManufacturerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManufacturerButtonActionPerformed(evt);
            }
        });

        addclientButton.setText("Add Client");
        addclientButton.setMaximumSize(new java.awt.Dimension(420, 420));
        addclientButton.setMinimumSize(new java.awt.Dimension(420, 420));
        addclientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclientButtonActionPerformed(evt);
            }
        });

        receiveShipmentButton.setText("Receive Shipment");
        receiveShipmentButton.setMaximumSize(new java.awt.Dimension(420, 420));
        receiveShipmentButton.setMinimumSize(new java.awt.Dimension(420, 420));
        receiveShipmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveShipmentButtonActionPerformed(evt);
            }
        });

        listSuppliersButton.setText("List Suppliers for a Product");
        listSuppliersButton.setMaximumSize(new java.awt.Dimension(420, 420));
        listSuppliersButton.setMinimumSize(new java.awt.Dimension(420, 420));
        listSuppliersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSuppliersButtonActionPerformed(evt);
            }
        });

        listallProductwithQuantityButton.setText("List all Products");
        listallProductwithQuantityButton.setMaximumSize(new java.awt.Dimension(420, 420));
        listallProductwithQuantityButton.setMinimumSize(new java.awt.Dimension(420, 420));
        listallProductwithQuantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listallProductwithQuantityButtonActionPerformed(evt);
            }
        });

        shipfromWaitListButton.setText("Ship From Wait List");
        shipfromWaitListButton.setMaximumSize(new java.awt.Dimension(420, 420));
        shipfromWaitListButton.setMinimumSize(new java.awt.Dimension(420, 420));
        shipfromWaitListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipfromWaitListButtonActionPerformed(evt);
            }
        });

        processClientOrderButton.setText("Process Client Order");
        processClientOrderButton.setMaximumSize(new java.awt.Dimension(420, 420));
        processClientOrderButton.setMinimumSize(new java.awt.Dimension(420, 420));
        processClientOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processClientOrderButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        topLabel.setText("Logged in as Sales Clerk: Add Client");

        backButton1.setText("Back");
        backButton1.setEnabled(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        becomeClientButton.setText("Become Client");
        becomeClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becomeClientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(topLabel)
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addManufacturerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addclientButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                .addComponent(becomeClientButton))
                            .addComponent(listclientwithoutstandingbalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(processPaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(processClientOrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(receiveShipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(shipfromWaitListButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(savedatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loaddatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(listSuppliersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listallProductwithQuantityButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton1)
                    .addComponent(logoutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addclientButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(becomeClientButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addManufacturerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(processClientOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiveShipmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shipfromWaitListButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(processPaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listclientwithoutstandingbalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listallProductwithQuantityButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listSuppliersButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savedatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loaddatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listclientwithoutstandingbalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listclientwithoutstandingbalanceButtonActionPerformed
        ClerkMenuState.instance().listClientwithOutstandingBalancePressed();
}//GEN-LAST:event_listclientwithoutstandingbalanceButtonActionPerformed

    private void savedatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedatabaseButtonActionPerformed
       ClerkMenuState.instance().savePressed();
}//GEN-LAST:event_savedatabaseButtonActionPerformed

    private void loaddatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaddatabaseButtonActionPerformed
        ClerkMenuState.instance().loadPressed();
}//GEN-LAST:event_loaddatabaseButtonActionPerformed

    private void processPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processPaymentButtonActionPerformed
        ClerkMenuState.instance().processPaymentPressed();
}//GEN-LAST:event_processPaymentButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
       ClerkMenuState.instance().addProductPressed();
}//GEN-LAST:event_addProductButtonActionPerformed

    private void addManufacturerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManufacturerButtonActionPerformed
        ClerkMenuState.instance().addManufacturerPressed();
}//GEN-LAST:event_addManufacturerButtonActionPerformed

    private void addclientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclientButtonActionPerformed
         ClerkMenuState.instance().addClientPressed();
}//GEN-LAST:event_addclientButtonActionPerformed

    private void receiveShipmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveShipmentButtonActionPerformed
         ClerkMenuState.instance().receiveShipmentPressed();
}//GEN-LAST:event_receiveShipmentButtonActionPerformed

    private void listSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSuppliersButtonActionPerformed
         ClerkMenuState.instance().listManufacturerforProductPressed();
}//GEN-LAST:event_listSuppliersButtonActionPerformed

    private void listallProductwithQuantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listallProductwithQuantityButtonActionPerformed
         ClerkMenuState.instance().listProductwithQuantityPressed();
}//GEN-LAST:event_listallProductwithQuantityButtonActionPerformed

    private void shipfromWaitListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipfromWaitListButtonActionPerformed
         ClerkMenuState.instance().shipfromWaitlistPressed();
}//GEN-LAST:event_shipfromWaitListButtonActionPerformed

    private void processClientOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processClientOrderButtonActionPerformed
         ClerkMenuState.instance().processClientOrderPressed();
}//GEN-LAST:event_processClientOrderButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
         ClerkMenuState.instance().logoutPressed();
}//GEN-LAST:event_logoutButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
}//GEN-LAST:event_backButton1ActionPerformed

    private void becomeClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_becomeClientButtonActionPerformed
        ClerkMenuState.instance().becomeClientPressed();
    }//GEN-LAST:event_becomeClientButtonActionPerformed

    public void setup(){
        topLabel.setText("Logged in as " + Security.instance().getLoginString() + ": Clerk Menu");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addManufacturerButton;
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton addclientButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton becomeClientButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton listSuppliersButton;
    private javax.swing.JButton listallProductwithQuantityButton;
    private javax.swing.JButton listclientwithoutstandingbalanceButton;
    private javax.swing.JButton loaddatabaseButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton processClientOrderButton;
    private javax.swing.JButton processPaymentButton;
    private javax.swing.JButton receiveShipmentButton;
    private javax.swing.JButton savedatabaseButton;
    private javax.swing.JButton shipfromWaitListButton;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables

}
