package gui;
public class ManagerMenuPanel extends javax.swing.JPanel {

    /** Creates new form LoginPanel1 */
    public ManagerMenuPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderManufacturerButton = new javax.swing.JButton();
        addSupplierButton = new javax.swing.JButton();
        removeSupplierButton = new javax.swing.JButton();
        modifyPriceButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        backButton1 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        topLabel = new javax.swing.JLabel();
        becomeClerkButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(420, 420));
        setMinimumSize(new java.awt.Dimension(420, 420));
        setPreferredSize(new java.awt.Dimension(420, 420));

        orderManufacturerButton.setText("Order from Manufacturer");
        orderManufacturerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderManufacturerButtonActionPerformed(evt);
            }
        });

        addSupplierButton.setText("Add Manufacturer as a Supplier");
        addSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierButtonActionPerformed(evt);
            }
        });

        removeSupplierButton.setText("Remove Manufacturer as a Supplier");
        removeSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSupplierButtonActionPerformed(evt);
            }
        });

        modifyPriceButton.setText("Modify Sale Price");
        modifyPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPriceButtonActionPerformed(evt);
            }
        });

        backButton1.setText("Back");
        backButton1.setEnabled(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        topLabel.setText("Logged in as Sales Clerk: Add Client");

        becomeClerkButton.setText("Become Clerk");
        becomeClerkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becomeClerkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(topLabel)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSupplierButton)
                    .addComponent(modifyPriceButton)
                    .addComponent(orderManufacturerButton)
                    .addComponent(removeSupplierButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(becomeClerkButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(backButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(becomeClerkButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderManufacturerButton)
                        .addGap(18, 18, 18)
                        .addComponent(modifyPriceButton)
                        .addGap(18, 18, 18)
                        .addComponent(addSupplierButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeSupplierButton)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderManufacturerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderManufacturerButtonActionPerformed
        ManagerMenuState.instance().orderManufacturerPressed();
    }//GEN-LAST:event_orderManufacturerButtonActionPerformed

    private void modifyPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPriceButtonActionPerformed
        ManagerMenuState.instance().modifyPricePressed();
    }//GEN-LAST:event_modifyPriceButtonActionPerformed

    private void addSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierButtonActionPerformed
        ManagerMenuState.instance().addSupplierPressed();
    }//GEN-LAST:event_addSupplierButtonActionPerformed

    private void removeSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSupplierButtonActionPerformed
        ManagerMenuState.instance().removeSupplierPressed();
    }//GEN-LAST:event_removeSupplierButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
}//GEN-LAST:event_backButton1ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        ManagerMenuState.instance().logoutPressed();
}//GEN-LAST:event_logoutButtonActionPerformed

    private void becomeClerkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_becomeClerkButtonActionPerformed
        ManagerMenuState.instance().becomeClerkPressed();
    }//GEN-LAST:event_becomeClerkButtonActionPerformed

    public void setup(){
        topLabel.setText("Logged in as " + Security.instance().getLoginString() + ": Manager menu");
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPanel1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupplierButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton becomeClerkButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton modifyPriceButton;
    private javax.swing.JButton orderManufacturerButton;
    private javax.swing.JButton removeSupplierButton;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables

}
